#!/usr/bin/env python
from Common import FTVL, TemplateType

mod_mon = [
    {
        "params": {
            "pv": "$(D):Mod-MinMaxNom-Mon",
            "param": "getModMinMaxNom",
            "scan": "30 second",
            "nelm": "12",
            "ftvl": FTVL.DOUBLE,
        },
        "items": [
            {"pv": "$(D):Mod-MinVolt-Mon", "desc": "Voltage Min", "egu": "V"},
            {"pv": "$(D):Mod-MinCurrent-Mon", "desc": "Current Min", "egu": "A"},
            {"pv": "$(D):Mod-MinPwr-Mon", "desc": "Power Min", "egu": "kW"},
            {"pv": "$(D):Mod-MinRes-Mon", "desc": "Resistance Min", "egu": "mOhm"},
            {"pv": "$(D):Mod-MaxVolt-Mon", "desc": "Voltage Max", "egu": "V"},
            {"pv": "$(D):Mod-MaxCurrent-Mon", "desc": "Current Max", "egu": "A"},
            {"pv": "$(D):Mod-MaxPwr-Mon", "desc": "Power Max", "egu": "kW"},
            {"pv": "$(D):Mod-MaxRes-Mon", "desc": "Resistance Max", "egu": "mOhm"},
            {"pv": "$(D):Mod-NomVolt-Mon", "desc": "Voltage Nominal", "egu": "V"},
            {"pv": "$(D):Mod-NomCurrent-Mon", "desc": "Current Nominal", "egu": "A"},
            {"pv": "$(D):Mod-NomPwr-Mon", "desc": "Power Nominal", "egu": "kW"},
            {"pv": "$(D):Mod-NomRes-Mon", "desc": "Resistance Nominal", "egu": "mOhm"},
        ],
    },
    {
        "params": {
            "pv": "$(D):Mod-Mon",
            "param": "getModReadings",
            "scan": "5 second",
            "nelm": "5",
            "ftvl": FTVL.DOUBLE,
        },
        "items": [
            {"pv": "$(D):Mod-OutVolt-Mon", "desc": "Module out voltage", "egu": "V"},
            {"pv": "$(D):Mod-OutCurrent-Mon", "desc": "Module out current", "egu": "A"},
            {"pv": "$(D):Mod-OutPwr-Mon", "desc": "Module out power", "egu": "kW"},
            {
                "pv": "$(D):Mod-ResPreset-Mon",
                "desc": "Module resistence preset",
                "egu": "mOhm",
            },
            {
                "pv": "$(D):Mod-State-Mon",
                "desc": "Module state",
                "type": TemplateType.MBBI_ITEM,
                "onst": "",
                "twst": "POWERUP",
                "frst": "READY",
                "eist": "RUN",
                "nist": "",
                "test": "WARN",
                "tvst": "ERROR",
                "ftst": "STOP",
            },
        ],
    },
    {
        "pv": "$(D):Mod-ControlMode-Mon",
        "desc": "Module control mode",
        "param": "getModControlMode",
        "type": TemplateType.MBBI,
        "zrst": "Constant Voltage",
        "onst": "Constant Current",
        "twst": "Constant Pwr",
        "thst": "Usense limit active",
        "frst": "Psense limit active",
        "fvst": "Current derating active",
        "scan": "10 second",
    },
    {
        "pv": "$(D):Mod-VoltageRef-Mon",
        "desc": "Reference val. for voltage",
        "type": TemplateType.ANALOG_GET,
        "param": "getModVoltageRef",
        "egu": "V",
        "prio": "HIGH",
        "scan": "60 second",
    },
    {
        "pv": "$(D):Mod-CurrentRef-Mon",
        "desc": "Reference val. for current",
        "type": TemplateType.ANALOG_GET,
        "param": "getModCurrentRef",
        "egu": "A",
        "prio": "HIGH",
        "scan": "60 second",
    },
    {
        "pv": "$(D):Mod-ResistanceRef-Mon",
        "desc": "Reference val. for resistance",
        "type": TemplateType.ANALOG_GET,
        "param": "getModResistanceRef",
        "egu": "mOhm",
        "prio": "HIGH",
        "scan": "60 second",
    },
    {
        "pv": "$(D):Mod-PwrRef-Mon",
        "desc": "Reference val. for power",
        "type": TemplateType.ANALOG_GET,
        "param": "getModPowerRef",
        "egu": "kW",
        "prio": "HIGH",
        "scan": "60 second",
    },
]
mod_get_set = []
sys_get_set = [
    {
        "pv": "$(D):Sys-OutVoltEnbl",
        "desc": "Enable/Disable output voltage",
        "type": TemplateType.BINARY_GET_SET,
        "znam": "Disable",
        "onam": "Enable",
        "param": "SysOutVoltEnable",
        "prio": "HIGH",
        "scan": "60 second",
    },
    {
        "pv": "$(D):Sys-VoltageRef",
        "desc": "Reference val. for voltage",
        "type": TemplateType.ANALOG_GET_SET,
        "param": "SysVoltageRef",
        "egu": "V",
        "prio": "HIGH",
        "scan": "60 second",
    },
    {
        "pv": "$(D):Sys-CurrentRef",
        "desc": "Reference val. for current",
        "type": TemplateType.ANALOG_GET_SET,
        "param": "SysCurrentRef",
        "egu": "A",
        "prio": "HIGH",
        "scan": "60 second",
    },
    {
        "pv": "$(D):Sys-ResistanceRef",
        "desc": "Reference val. for resistance",
        "type": TemplateType.ANALOG_GET_SET,
        "param": "SysResistanceRef",
        "egu": "mOhm",
        "prio": "HIGH",
        "scan": "60 second",
    },
    {
        "pv": "$(D):Sys-PwrRef",
        "desc": "Reference val. for power",
        "type": TemplateType.ANALOG_GET_SET,
        "param": "SysPowerRef",
        "egu": "kW",
        "prio": "HIGH",
        "scan": "60 second",
    },
    {
        "pv": "$(D):Sys-VoltSlopeWf-Mon_proc",
        "type": TemplateType.BINARY_FLNK,
        "prio": "LOW",
        "flnk": "$(D):Sys-VoltSlopeWf-Mon",
        "scan": "60 second",
    },
    {
        "params": {
            "pv": "$(D):Sys-VoltSlopeWf-Mon",
            "param": "getSlopeVolt",
            "scan": "Passive",
            "nelm": "4",
            "ftvl": FTVL.DOUBLE,
            "prio": "HIGH",
        },
        "items": [
            {
                "pv": "$(D):Sys-StartupVoltSlopeRaw-RB",
                "desc": "Set values when enabling output volt",
                "egu": "units",
                "type": TemplateType.LONG_IN_ITEM,
            },
            {
                "pv": "$(D):Sys-VoltSlopeRaw-RB",
                "desc": "Set values when they are changed",
                "egu": "units",
                "type": TemplateType.LONG_IN_ITEM,
            },
            {
                "pv": "$(D):Sys-StartupVoltSlope-RB",
                "desc": "Set values when enabling output volt",
                "egu": "V/ms",
                "prec": "2",
            },
            {
                "pv": "$(D):Sys-VoltSlope-RB",
                "desc": "Set values when they are changed",
                "egu": "V/ms",
                "prec": "2",
            },
        ],
    },
    {
        "pv": "$(D):Sys-SlopeVoltMax-Mon",
        "desc": "Voltage slope max",
        "type": TemplateType.ANALOG_GET,
        "param": "getSlopeVoltMax",
        "egu": "V/ms",
        "prio": "HIGH",
        "prec": "2",
        "scan": "30 second",
    },
    {
        "pv": "$(D):Sys-SlopeVoltMin-Mon",
        "desc": "Voltage slope min",
        "type": TemplateType.ANALOG_GET,
        "param": "getSlopeVoltMin",
        "egu": "V/ms",
        "prio": "HIGH",
        "prec": "2",
        "scan": "30 second",
    },
    {
        "pv": "$(D):Sys-StartupVoltSlope-SP",
        "desc": "Set values when enabling output volt",
        "type": TemplateType.ANALOG_SET,
        "param": "setSlopeStartupVoltMs",
        "egu": "V/ms",
        "prio": "HIGH",
        "prec": "2",
        "flnk": "$(D):Sys-StartupVoltSlope-SP_",
    },
    {
        "pv": "$(D):Sys-StartupVoltSlope-SP_",
        "desc": "Actual setpoint to be sent",
        "type": TemplateType.ANALOG_GET,
        "param": "getSlopeStartupVoltSp",
        "egu": "V/ms",
        "prio": "HIGH",
        "prec": "2",
        "scan": ".5 second",
    },
    {
        "pv": "$(D):Sys-VoltSlope-SP",
        "desc": "Set values when they are changed",
        "type": TemplateType.ANALOG_SET,
        "param": "setSlopeVoltMs",
        "egu": "V/ms",
        "prio": "HIGH",
        "prec": "2",
    },
    {
        "pv": "$(D):Sys-VoltSlope-SP_",
        "desc": "Actual setpoint to be sent",
        "type": TemplateType.ANALOG_GET,
        "param": "getSlopeVoltSp",
        "egu": "V/ms",
        "prio": "HIGH",
        "prec": "2",
        "scan": ".5 second",
    },
    {
        "pv": "$(D):Sys-StartupVoltSlopeRaw-SP",
        "desc": "Set values when enabling output volt",
        "type": TemplateType.LONG_SET,
        "param": "setSlopeStartupVoltRaw",
        "egu": "units",
        "prio": "HIGH",
        "drvh": "32000",
        "drvl": "1",
    },
    {
        "pv": "$(D):Sys-VoltSlopeRaw-SP",
        "desc": "Set values when they are changed",
        "type": TemplateType.LONG_SET,
        "param": "setSlopeVoltRaw",
        "egu": "units",
        "prio": "HIGH",
        "drvh": "32000",
        "drvl": "1",
    },
    {
        "pv": "$(D):Sys-WriteVoltSlope-Cmd",
        "desc": "Apply voltage slope settings",
        "type": TemplateType.BO_CMD,
        "param": "cmdSlopeVoltWrite",
        "prio": "HIGH",
        "flnk": "$(D):Sys-VoltSlopeWf-Mon",
    },
    {
        "pv": "$(D):Sys-CurrSlopeWf-Mon_proc",
        "type": TemplateType.BINARY_FLNK,
        "prio": "LOW",
        "flnk": "$(D):Sys-CurrSlopeWf-Mon",
        "scan": "60 second",
    },
    {
        "params": {
            "pv": "$(D):Sys-CurrSlopeWf-Mon",
            "param": "getSlopeCurrent",
            "scan": "Passive",
            "nelm": "4",
            "ftvl": FTVL.DOUBLE,
            "prio": "HIGH",
        },
        "items": [
            {
                "pv": "$(D):Sys-StartupCurrSlopeRaw-RB",
                "desc": "Set values when enabling output volt",
                "egu": "units",
                "type": TemplateType.LONG_IN_ITEM,
            },
            {
                "pv": "$(D):Sys-CurrSlopeRaw-RB",
                "desc": "Set values when they are changed",
                "egu": "units",
                "type": TemplateType.LONG_IN_ITEM,
            },
            {
                "pv": "$(D):Sys-StartupCurrSlope-RB",
                "desc": "Set values when enabling output volt",
                "egu": "A/ms",
                "prec": "2",
            },
            {
                "pv": "$(D):Sys-CurrSlope-RB",
                "desc": "Set values when they are changed",
                "egu": "A/ms",
                "prec": "2",
            },
        ],
    },
    {
        "pv": "$(D):Sys-SlopeCurrMax-Mon",
        "desc": "Currage slope max",
        "type": TemplateType.ANALOG_GET,
        "param": "getSlopeCurrentMax",
        "egu": "A/ms",
        "prio": "HIGH",
        "prec": "2",
        "scan": "30 second",
    },
    {
        "pv": "$(D):Sys-SlopeCurrMin-Mon",
        "desc": "Currage slope min",
        "type": TemplateType.ANALOG_GET,
        "param": "getSlopeCurrentMin",
        "egu": "A/ms",
        "prio": "HIGH",
        "prec": "2",
        "scan": "30 second",
    },
    {
        "pv": "$(D):Sys-StartupCurrSlope-SP",
        "desc": "Set values when enabling output current",
        "type": TemplateType.ANALOG_SET,
        "param": "setSlopeStartupCurrentMs",
        "egu": "A/ms",
        "prio": "HIGH",
        "prec": "2",
        "flnk": "$(D):Sys-StartupCurrSlope-SP_",
    },
    {
        "pv": "$(D):Sys-StartupCurrSlope-SP_",
        "desc": "Actual setpoint to be sent",
        "type": TemplateType.ANALOG_GET,
        "param": "getSlopeStartupCurrentSp",
        "egu": "A/ms",
        "prio": "HIGH",
        "prec": "2",
        "scan": ".5 second",
    },
    {
        "pv": "$(D):Sys-CurrSlope-SP",
        "desc": "Set values when they are changed",
        "type": TemplateType.ANALOG_SET,
        "param": "setSlopeCurrentMs",
        "egu": "A/ms",
        "prio": "HIGH",
        "prec": "2",
        "flnk": "$(D):Sys-CurrSlope-SP_",
    },
    {
        "pv": "$(D):Sys-CurrSlope-SP_",
        "desc": "Actual setpoint to be sent",
        "type": TemplateType.ANALOG_GET,
        "param": "getSlopeCurrentSp",
        "egu": "A/ms",
        "prio": "HIGH",
        "prec": "2",
        "scan": ".5 second",
    },
    {
        "pv": "$(D):Sys-StartupCurrSlopeRaw-SP",
        "desc": "Set values when enabling output current",
        "type": TemplateType.LONG_SET,
        "param": "setSlopeStartupCurrentRaw",
        "egu": "units",
        "prio": "HIGH",
        "drvh": "32000",
        "drvl": "1",
    },
    {
        "pv": "$(D):Sys-CurrSlopeRaw-SP",
        "desc": "Set values when they are changed",
        "type": TemplateType.LONG_SET,
        "param": "setSlopeCurrentRaw",
        "egu": "units",
        "prio": "HIGH",
        "drvh": "32000",
        "drvl": "1",
    },
    {
        "pv": "$(D):Sys-WriteCurrSlope-Cmd",
        "desc": "Apply current slope settings",
        "type": TemplateType.BO_CMD,
        "param": "cmdSlopeCurrentWrite",
        "prio": "HIGH",
        "flnk": "$(D):Sys-CurrSlopeWf-Mon",
    },
]

sys_cmd = [
    {
        "pv": "$(D):Save-Cmd",
        "desc": "Save settings to non-volatile memory",
        "type": TemplateType.BO_CMD,
        "param": "cmdStoreParam",
        "prio": "HIGH",
    },
    {
        "pv": "$(D):Clear-Cmd",
        "desc": "Clear Errors and/or warnings",
        "type": TemplateType.BO_CMD,
        "param": "cmdClearErrors",
        "prio": "HIGH",
    },
]

sys_mon = [
    {
        "params": {
            "pv": "$(D):Sys-MinMaxNom-Mon",
            "param": "getSysMinMaxNom",
            "scan": "30 second",
            "nelm": "12",
            "ftvl": FTVL.DOUBLE,
        },
        "items": [
            {"pv": "$(D):Sys-MinVolt-Mon", "desc": "Voltage Min", "egu": "V"},
            {"pv": "$(D):Sys-MinCurrent-Mon", "desc": "Current Min", "egu": "A"},
            {"pv": "$(D):Sys-MinPwr-Mon", "desc": "Power Min", "egu": "kW"},
            {"pv": "$(D):Sys-MinRes-Mon", "desc": "Resistance Min", "egu": "mOhm"},
            {"pv": "$(D):Sys-MaxVolt-Mon", "desc": "Voltage Max", "egu": "V"},
            {"pv": "$(D):Sys-MaxCurrent-Mon", "desc": "Current Max", "egu": "A"},
            {"pv": "$(D):Sys-MaxPwr-Mon", "desc": "Power Max", "egu": "kW"},
            {"pv": "$(D):Sys-MaxRes-Mon", "desc": "Resistance Max", "egu": "mOhm"},
            {"pv": "$(D):Sys-NomVolt-Mon", "desc": "Voltage Nominal", "egu": "V"},
            {"pv": "$(D):Sys-NomCurrent-Mon", "desc": "Current Nominal", "egu": "A"},
            {"pv": "$(D):Sys-NomPwr-Mon", "desc": "Power Nominal", "egu": "kW"},
            {"pv": "$(D):Sys-NomRes-Mon", "desc": "Resistance Nominal", "egu": "mOhm"},
        ],
    },
    {
        "params": {
            "pv": "$(D):Sys-Mon",
            "param": "getSysReadings",
            "scan": "5 second",
            "nelm": "5",
            "ftvl": FTVL.DOUBLE,
        },
        "items": [
            {"pv": "$(D):Sys-OutVolt-Mon", "desc": "System out voltage", "egu": "V"},
            {"pv": "$(D):Sys-OutCurrent-Mon", "desc": "System out current", "egu": "A"},
            {"pv": "$(D):Sys-OutPwr-Mon", "desc": "System out power", "egu": "kW"},
            {
                "pv": "$(D):Sys-ResPreset-Mon",
                "desc": "System resistence preset",
                "egu": "mOhm",
            },
            {
                "pv": "$(D):Sys-State-Mon",
                "desc": "System state",
                "type": TemplateType.MBBI_ITEM,
                "onst": "",
                "twst": "POWERUP",
                "frst": "READY",
                "eist": "RUN",
                "nist": "",
                "test": "WARN",
                "tvst": "ERROR",
                "ftst": "STOP",
            },
        ],
    },
    {
        "pv": "$(D):Sys-ControlMode-Mon",
        "param": "getSysControlMode",
        "desc": "System control mode",
        "type": TemplateType.MBBI,
        "zrst": "Constant Voltage",
        "onst": "Constant Current",
        "twst": "Constant Pwr",
        "thst": "Usense limit active",
        "frst": "Psense limit active",
        "fvst": "Current derating active",
        "scan": "10 second",
    },
]


temperature = {
    "params": {
        "pv": "$(D):T-Mon",
        "param": "getTemperatures",
        "scan": "5 second",
        "nelm": "3",
        "ftvl": FTVL.DOUBLE,
    },
    "items": [
        {"pv": "$(D):IGBTT-Mon", "desc": "IGBT temperature", "egu": "C"},
        {"pv": "$(D):RectifierT-Mon", "desc": "Rectifier temperature", "egu": "C"},
        {"pv": "$(D):PCBT-Mon", "desc": "PCB temperature", "egu": "C"},
    ],
}


generic_mon = [
    {
        "pv": "$(D):ActiveInterface-Mon",
        "desc": "Active interface",
        "scan": "60 second",
        "type": TemplateType.MBBI,
        "param": "getControlInput",
        "zrst": "Analog/Digital Inputs",
        "onst": "HMI/HME",
        "twst": "RS232",
        "thst": "",
        "frst": "",
        "frvl": "",
    },
    {
        "pv": "$(D):DCLinkVolt-Mon",
        "desc": "DC link voltage measure",
        "param": "getDCLinkVoltage",
        "egu": "V",
        "scan": "5 second",
    },
    {
        "pv": "$(D):PrimaryCurr-Mon",
        "desc": "Transformer primary current",
        "param": "getPrimaryCurrent",
        "egu": "A",
        "scan": "5 second",
    },
    {
        "pv": "$(D):ModuleID-Mon",
        "desc": "Module ID - switch",
        "param": "getModuleID",
        "scan": "60 second",
        "type": TemplateType.LONG_IN,
    },
    {
        "pv": "$(D):DSPVer-Mon",
        "desc": "DSP Firmware Version",
        "param": "getDSPVersion",
        "scan": "60 second",
        "type": TemplateType.STRING_IN,
    },
    {
        "pv": "$(D):ModulatorVer-Mon",
        "desc": "Modulator Version",
        "param": "getModulatorVersion",
        "scan": "60 second",
        "type": TemplateType.STRING_IN,
    },
    {
        "pv": "$(D):PheripherieVer-Mon",
        "desc": "Pheripherie Version",
        "param": "getPheripherieVersion",
        "scan": "60 second",
        "type": TemplateType.STRING_IN,
    },
    {
        "pv": "$(D):BootloaderVer-Mon",
        "desc": "Bootloader Version",
        "param": "getBootloaderVersion",
        "scan": "60 second",
        "type": TemplateType.STRING_IN,
    },
    {
        "pv": "$(D):DLLVer-Mon",
        "desc": "DLL Version",
        "param": "getDLLVersion",
        "scan": "60 second",
        "type": TemplateType.STRING_IN,
    },
]

generic_cmd = [
    {
        "pv": "$(D):Connect-Cmd",
        "desc": "Attempt to connect to the device",
        "type": TemplateType.BO_CMD,
        "param": "cmdConnect",
        "prio": "HIGH",
    },
    {
        "pv": "$(D):Disconnect-Cmd",
        "desc": "Disconnect from device",
        "type": TemplateType.BO_CMD,
        "param": "cmdDisconnect",
        "prio": "HIGH",
    },
    {
        "pv": "$(D):ReadErrors-Cmd",
        "desc": "Read Errors from TC",
        "type": TemplateType.BO_CMD,
        "param": "cmdReadErrors",
        "prio": "HIGH",
    },
]

generic_get_set = [
    {
        "pv": "$(D):ErrorHistory-Mon",
        "param": "getFlashErrorHistory",
        "scan": "Passive",
        "nelm": "300",
        "ftvl": FTVL.STRING,
        "prio": "HIGH",
        "type": TemplateType.WF_STRING_DB,
    },
    {
        "pv": "$(D):ErrorHistoryMax-SP",
        "desc": "Maximum entries from error history",
        "type": TemplateType.LONG_SET,
        "param": "setFlashErrorHistoryMax",
        "prio": "HIGH",
    },
    {
        "pv": "$(D):AutoReconnect",
        "desc": "Enable/Disable auto reconnect to device",
        "type": TemplateType.BINARY_GET_SET,
        "param": "AutoReconnect",
        "onam": "Enable",
        "znam": "Disable",
        "prio": "HIGH",
        "scan": "60 second",
    },
]
